theme: reebok_theme
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer: {  }
  my_email: {  }
