schemas:
  bootstrap: 8000
  reebok_theme: 8000
favicon:
  mimetype: image/jpeg
  path: 'public://2018-07/kisspng-reebok-classic-logo-reebok-crossfit-brand-reebook-5b221733d92b99.9060304615289608198895.jpg'
  url: 'http://reebok.loc/sites/default/files/2018-07/kisspng-reebok-classic-logo-reebok-crossfit-brand-reebook-5b221733d92b99.9060304615289608198895.jpg'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://inline-images/aditime_logo.png'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
region_wells:
  navigation: ''
  navigation_collapsible: ''
  info_block: ''
  navigation_with_goods: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  left_block: ''
  right_block: ''
  taxonomy_for_you: ''
  owl_carousel_tabs: ''
  info_reebok_block: ''
  information_block_reebok_empty_block: ''
  information_block_reebok: ''
  footer: ''
  left_footer_block: ''
  top_right_footer_block: ''
  bottom_right_footer_block: ''
  info_footer_block: ''
  copyright_footer_block: ''
