<?php

use Drupal\Component\Utility\Html;

/**
 * @param $key
 * @param $message
 * @param $params
 * Implements hook_mail()
 */
function my_email_mail($key, &$message, $params)
{
  switch ($key) {
    case 'mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['title'];

      $theme_body = [
        '#theme' => 'my_email',
        '#body' => $params['body']['body'],
        '#name' => $params['body']['name'],
        '#country' => $params['body']['country'],
      ];

      $mail_body = \Drupal::service('renderer')->render($theme_body);
      $message['body'][] = Html::escape($mail_body);
      /*var_dump($mail_body);
      die();*/
      break;
  }
}
  /**
   * Implements hook_theme().
   */
  function my_email_theme() {
    return [
      'my_email' => [
        'variables' => [
          'body' => NULL,
          'name' => NULL,
          'country' => NULL,
          ],
        ],
      ];
    }
